### ISSUE TITLE
NullPointerException When play on second audio

### ISSUE THREAD

**Issue by xinlangzi** [zmxv/react-native-sound#367]
No problem to Play on first audio, but app crash when play the second audio. 

.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference at 
```
com.zmxv.RNSound.RNSoundModule.onAudioFocusChange(RNSoundModule.java:391)
```

**Comment by Damnum** [comment]
Same problem here. Android 6.0.1.

**Comment by xinlangzi** [comment]
@Damnum 

Please upgrade to head code which solve the problem in my android 5.0.1. 
In our package.json, please update as to:

```
"react-native-sound": "git+ssh://git@github.com/zmxv/react-native-sound.git#HEAD",
```

**Comment by xinlangzi** [comment]
@Damnum 

Have you set this Sound.setCategory('Playback', true), the app will crash down if I set Sound.setCategory('Playback', false);

**Comment by Damnum** [comment]
Yeah that's because if you set it to true, the method `onAudioFocusChange ` will not do anything:

https://github.com/zmxv/react-native-sound/blob/master/android/src/main/java/com/zmxv/RNSound/RNSoundModule.java#L390

My PR should fix the crash for `Sound.setCategory('Playback', false)` as well:

https://github.com/zmxv/react-native-sound/pull/370

**Comment by ofirdagan** [comment]
Following
