### ISSUE TITLE
Sound starts playing randomly when opening app when headphones are plugged in

### ISSUE THREAD

**Issue by schumannd** [zmxv/react-native-sound#423]
I am using this package together with `react-native-music-control` which has caused issues in the past, so there is that. I am curious whether others experience this issue as well.

After digging through code and docs a bit I found the possible reason in `RNSoundm` lines 21-25:
```
    if (audioSessionRouteChangeReason == AVAudioSessionRouteChangeReasonNewDeviceAvailable){
        if (player) {
            [player play];
        }
    }
```

Anyone knows what these lines are used for? (@kurokky, I think you added these lines) It seems to trigger unwanted sound plays for our app.

I created a PR which removes these files which can be merged in case no one needs them.

**Comment by kurokky** [comment]
Hi @schumannd 
Did you see https://github.com/zmxv/react-native-sound/issues/201 
There is no place calling the random method in my request.
Unfortunately, I have never used react-native-music-control.
So, I don't know why to happen in your environment it.
When I checked it did not do such a move and I have not requested If I found it.
More people would comment if my request was the cause.
However, from that time a long time has passed but never once.
I hope that you should test without react-native-music-control rather than deleting the code.

**Comment by schumannd** [comment]
Hello @kurokky. In the meantimeI I removed react-native-music-control as it caused other issues as well. I thought maybe you could explain what these lines do. For me it looks like it is simply starting playback when a new device is plugged in? Or when is `AVAudioSessionRouteChangeReasonNewDeviceAvailable` the RouteChangeReason or what exactly does [player play] do in that situation?

**Comment by ngandhy** [comment]
@schumannd - seems kind of backwards to remove a feature from this library because another library didn't play well with it

**Comment by ngandhy** [comment]
@schumannd - see #201

**Comment by schumannd** [comment]
@ngandhy the issue occurred independently of another package.
