### ISSUE TITLE
Sounds don't play fast enough

### ISSUE THREAD

**Issue by chetstone** [zmxv/react-native-sound#9]
My app plays a short click sound when the user taps a button. I find that if she taps the button more than about 4 times a second, the clicks get dropped.

I was using react-native-audioplayer before and I switched to this one because it was [not mixing properly with other sounds on the device](https://github.com/andreaskeller/react-native-audioplayer/issues/13). I also like the ability to set the volume with this component.

But with react-native-audioplayer the user can tap much faster and the clicks keep up almost as fast as it is possible to tap the device.

Do you have any ideas on what might be causing the delay? As you suggest in the readme, I call `var sound = new Sound()` when the component mounts, then just call `sound.play()` when the button is tapped.

**Comment by zmxv** [comment]
I assume you're reusing the same Sound instance. In that case, if your click sound is longer than 250ms, and you tap faster than 4 times a second, some of the `play()` calls will be no-ops because the previous calls aren't finished. The solution is pretty simple: create and play a new Sound instance for each click. Or better yet, create a pool of reusable Sound instances to minimize delays.

**Comment by chetstone** [comment]
Thanks! That works great.
